IT-Start-Gjovik/startgjovik_website

.github/workflows/pr.yml
Med god PR checks så vil man kunne se at det er riktig satt opp. 
Både med ES lint og Typescript. 
Noen form for error må fikses før man kan kunne utføre PR. 
Inne i  `.github/workflows` finner du en fil med steg for å utføre checks:
- Es Lint
- Typescript
Begge checks innebærer å` npm install `og så utføre en kommando som er aktuell.
Se `pr.yml`
=> Pr workflow

contribute.md
Legge til en contribute fil med nødvendig informasjon for å gjøre det lettere for andre å være delaktig i projected.
=> Contribute fil

app/(site)/events/[eventPage]/page.tsx, app/(site)/page.tsx, components/UI/logo.tsx, components/events/eventCardList.tsx, components/footer/footer.tsx
=> Mobile first styling

app/(site)/events/[eventPage]/page.tsx, app/(site)/loading.tsx, app/(site)/page.tsx, components/UI/noEventsFound.tsx, components/events/eventCard.tsx, components/events/eventCardList.tsx, utils/date.ts
Det som skjedde i prod vat at man sendte uendlig mange spørringer til sanity.
Dette var på grunn av at async metoden ikkje var satt opp rikig.
Resultatet av buggen: 
Brukte en useEffect for å løse dette!
=> Fix fetch bug to sanity

app/(site)/events/[eventPage]/page.tsx, app/(site)/loading.tsx, app/(site)/page.tsx, app/(site)/test/page.tsx, components/loadingPage/loadingPage.tsx
Simple loading screen shown on loading data:
=> Loading page

CODEOWNERS, app/(site)/events/[eventPage]/page.tsx, app/(site)/loading.tsx, app/(site)/page.tsx, components/UI/noEventsFound.tsx, components/events/eventCard.tsx, components/events/eventCardList.tsx, components/loadingPage/loadingPage.tsx, package-lock.json, package.json, utils/date.ts
PR for adding v1.0.1 to production
Read version log here:
https://github.com/IT-Start-Gjovik/startgjovik_website/releases/tag/v1.0.1
=> V1.0.1 to Production

.github/dependabot.yml, app/(site)/events/[eventPage]/page.tsx, app/(site)/feilside/page.tsx, app/(site)/page.tsx, package-lock.json, package.json
=> Merge v1.0.2

.github/dependabot.yml, app/(site)/events/[eventPage]/page.tsx, app/(site)/feilside/page.tsx, app/(site)/page.tsx, package-lock.json, package.json
Update main branch 
Trenger ikke å forklare hver kodelinje, men en generell forkalring er god.)
=> Merge development into main

app/(site)/join/page.tsx, components/jumbotron/jumbotron.tsx
Created the join page. Can be found under the `/join` path!
Can be navigated to via the front page.
=> Create Join Page

components/footer/footer.tsx
Added the organization number in the footer of the page!
Org Number source: https://w2.brreg.no/enhet/sok/detalj.jsp?orgnr=918138358
=> Org number in footer

.github/pull_request_template.md
Changed the PR template to English. 
It is more universal and better coders outside the organization!
Changed the content of `./.github/pull request_template.md`
=> PR template to English

app/(site)/join/page.tsx
=> Fix: spelling mistake

utils/date.ts
We had a bug for day date. See issue #103 
Solved it by handling the minutes and removed the year from the card.
Could be improved later, maybe
=> fix: date time error

utils/date.ts
Refactored and improved code readability enhancement
I enhanced the code structure and made the getDateTimeFormat function more legible.
=> refactor: improved code readibility

app/(site)/layout.tsx, backend/schemas/event.ts, backend/schemas/verv.ts
Jeg har hovedsakelig opprettet denne pull requesten for å bli kjent med git-funksjonaliteten. Jeg har også gjort noen endringer i inputfeltene for å gjøre dem mer forståelige og brukervennlige. Planen min er å snakke med de som skal bruke denne delen av nettsiden, samle tilbakemeldinger og vurdere endringene for å forbedre den og gjøre den mer brukervennlig. Hvis det er noe som er gjort feil eller må endres, er det bare å si fra, så skal jeg se på det :)
=> Better descriptions for the input fields

app/(site)/baerekraft/page.tsx
A new route, /baerekraft, has been made. 
Made a new folder "baerekraft" under `app/(site)`, and a belonging `.tsx` file
=> feat: new baerekraft page

contribute.md
Made the contribute file in english. 
Used ChatGPT to translate the text into english. Works well with the text I provided.
=> update: english text for contribute file

app/(site)/baerekraft/page.tsx, components/jumbotron/sustainabilityMain.tsx
Added main sustainability-text.
New component.
=> add: main text for sustainability section

app/(site)/page.tsx
Ternary operator in the className. 
`${events && events.length > 1 ? 'xl:max-w-full' : 'xl:max-w-min'}`
=> Fix eventcard width

app/(site)/alle-arrangementer/page.tsx, app/(site)/baerekraft/page.tsx, app/(site)/bli-medlem/page.tsx, app/(site)/for-bedrifter/page.tsx, app/(site)/page.tsx, components/navbar/page.tsx
Updated pages with navigation bar
=> add navbar to all pages

app/(site)/for-bedrifter/page.tsx, components/map/map.tsx
I've added text and some info about Start Gjøvik. It doesn't quite work for phones, but i will take that up after exams. 
Just by writing inn the layout i've already made. and styling alittle bit.
=> For bedrifter mvp

CODEOWNERS
Changed code owner in `CODEOWNERS` file
=> change code owner

tailwind.config.js
What has changed? ✨
Custom breakpoints in `tailwind.config.js` has been deleted to get rid of breakpoints issues.
How did you solve/implement it? 🧠
Removed custom properties in `tailwind.config.js (theme: screens: {...})`
=> fix: remove custom breakpoints

components/navbar/page.tsx
Header (navbar) is now back to normal. 
Had to revert to standard breakpoints.
=> fix: fix header bugs

app/(site)/for-bedrifter/page.tsx, components/header/page.tsx, components/navbar/page.tsx, components/sustainability/carbonFootprint/carbonFootprint.tsx
Header (navbar) no longer blocks header texts. 
Added `pb-6` and `sticky` attributes to the `Header` component.
=> fix: header blocking header texts

app/(site)/page.tsx, components/events/eventCard.tsx
Both the event card list and event card component are now properly displayed. Every card's height matches the highest. 
Had to use `items-stretch` for the list, `flex-grow`on the event card component, and `layout='responsive'` for the image.
=> Fix event card (list)

app/(site)/for-bedrifter/page.tsx, components/listIcon/listIcon.tsx
The for company page currently doesn't support mobile screens. So, I've added dynamic scaling to the website. 
before:
after:
Tailwind can help you dynamicly change size of elements. From sm (small devices) to xl (large devices). Read more [here:](https://tailwindcss.com/docs/responsive-design)
=> For company size fix

components/UI/logo.tsx
`Logo`-component now accepts styles props  
Added an interface: 
```ts
interface LogoProps {
className?: string;
}
```
and pass the `className` prop to the className attribute of the `Image` component (if it exist).
=> add: logo component is customizable

backend/schemas/index.ts
The 'styre'-schema is now added to sanity studio (/admin). 
Added the schema to `schemas` array in `backend/../index.ts`
=> fix: 'styre' schema added

app/(site)/page.tsx, components/UI/noEventsFound.tsx, components/events/eventCard.tsx
I've finished adding the event section of the front page.
Just changed the background color and fixed some sizing.
=> finished event section

app/(site)/page.tsx, app/globals.css, components/header/page.tsx, components/navbar/dropDownMenu.tsx, components/navbar/hambugerMenuItems.ts, components/navbar/navbar.tsx
New dropdown menu. 
New components, functions, files etc.
=> Navbar sidebar

app/(site)/om-oss/page.tsx, components/navbar/dropDownMenu.tsx
The depth of sidebar. 
Added z-index to the component.
=> fix: add z-index for sidebar depth

components/frontPage/frontProp.tsx
* Just tailwind css and z-value
=> Fixing front prop

app/(site)/personvern/page.tsx, components/footer/footer.tsx
Privacy policy redesign 
Basic CSS styling.
=> refactor: privacy policy

app/(site)/layout.tsx, components/navbar/dropDownMenu.tsx, components/navbar/hambugerMenuItems.ts, components/navbar/navbar.tsx
Improved sidebar functionality, more specifically more cleaner code. 
New `div` that acts as the background layer when sidebar is active.
=> chore: improve sidebar functionality

app/(site)/bli-medlem/page.tsx, components/JoinList/joinlist.tsx, components/JoinList/joinlistelement.tsx
=> add: 'bli-medlem'-page redesign

app/(site)/arrangementer/[eventPage]/page.tsx
=> fix: image bigger

app/(site)/arrangementer/[eventPage]/page.tsx, app/(site)/page.tsx, backend/sanity-utils.ts, components/Button/button.tsx, components/UI/backbutton.tsx, components/UI/noEventsFound.tsx, components/eventSection/eventSection.tsx, components/events/eventCard.tsx, components/events/miniEventCard.tsx
=> feat: show previous/exp. events

app/(site)/arrangementer/[eventPage]/page.tsx
(Forklar hvorfor det er nødvendig. 
Gjerne med bilder eller illustrasjoner.)
(Teknisk overview av korleis det er løst.
Trenger ikke å forklare hver kodelinje, men en generell forklaring er godt nok.)
=> fix: ts error check

components/eventSection/eventSection.tsx
(Forklar hvorfor det er nødvendig. 
Gjerne med bilder eller illustrasjoner.)
(Teknisk overview av korleis det er løst.
Trenger ikke å forklare hver kodelinje, men en generell forklaring er godt nok.)
=> fix: remove dups

app/(site)/page.tsx~, components/UI/noEventsFound.tsx, components/eventSection/eventSection.tsx, components/events/eventCard.tsx, components/events/miniEventCard.tsx
(Forklar hvorfor det er nødvendig. 
Gjerne med bilder eller illustrasjoner.)
(Teknisk overview av korleis det er løst.
Trenger ikke å forklare hver kodelinje, men en generell forklaring er godt nok.)
=> feat: sort the events for better visibility

app/(site)/arrangementer/[eventPage]/page.tsx
(Forklar hvorfor det er nødvendig. 
Gjerne med bilder eller illustrasjoner.)
(Teknisk overview av korleis det er løst.
Trenger ikke å forklare hver kodelinje, men en generell forklaring er godt nok.)
=> img -> IMAGE
