app/(site)/events/[eventPage]/page.tsx, app/(site)/page.tsx
This is done with writing the `useEffect` correctly
Main page: 
```javascript
useEffect(() => {
if(!events){
getEventCards()
.then((data) => {
setEvents(data);
})
.catch((error) => {
console.error('Error fetching event cards:', error);
});
}
}, [events]);
```
Event Page: 
```javascript
useEffect(()=>{
if(!slug) redirect("/");
if(!eventPage) getEventPage(slug).then(data => setEventPage(data))
},[slug, eventPage])
```
=> Number of API calls reduced 

app/(site)/events/[eventPage]/page.tsx, app/(site)/feilside/page.tsx, app/(site)/page.tsx
Error page was created with the same code as before the bug. 
Use `router.push()` for navigating to the error page. 
Here is the style:
=> Error page

components/UI/backbutton.tsx, components/footer/footer.tsx, components/jumbotron/jumbotron.tsx, next.config.js
Some components still have light mode. Removed it for jombotron and footer
Also fixed the `next.config.js` to have the` appDir: true`
Read more about that here; 
https://nextjs.org/docs/messages/experimental-app-dir-config
=> Fix light mode 

components/JoinList/joinlist.tsx, components/JoinList/joinlistelement.tsx
Links for forms that are not marked as **ÅPEN**, should not be clickable 
Added the following tailwind CSS to the links that are not clickable 
`cursor-not-allowed pointer-events-none`
=> Bug: Links that are not open should not be clickable

backend/schemas/index.ts, backend/schemas/verv.ts
Created a schema for verv.  This will be part of the solution for making it easy to add a new Verv for the public. 
See the **verv.ts** in the backend folder.
Used sanity docs to achieve this!
=> Sanity: schema for Verv

backend/schemas/verv.ts
Had a small bug, where Sanity Studio expected a string but got a number.
Solved it by changing and adding toString() to each enum where the string is needed.
=> fix: bug with value of enum

backend/sanity-utils.ts, components/JoinList/joinlist.tsx, components/JoinList/joinlistelement.tsx, types/Verv.ts
Implemented the frontend code for using the fetch method to get the vervs and display them on the main page. 
Created the following fetch method:
```typescript
// Async function that gets all vervtypes from the backend
export async function getVervs(): Promise<VervType[]>{
const client = createClient({
projectId: "a42ubgcg",
dataset: "production",
apiVersion: "2023-07-06",
useCdn: false 
});
return client.fetch(
groq`*[_type == "verv"]{
_id,
title,
url,
type
}`
)
}
```
Then used them in the frontend code: 
```typescript
// Transforming a status code into the correct type 
const statusMap : Record<string, JoinStatus>= {
"0" : JoinStatus.OPEN,
"1" : JoinStatus.COMING_SOON,
"2" : JoinStatus.CLOSED
}
export default function JoinListElement({formUrl, title, status }:Props) {
let statusType: …
```
=> all fetched events are shown on the list of possible verv

app/(site)/events/[eventPage]/page.tsx, backend/sanity-utils.ts, backend/schemas/verv.ts, components/JoinList/joinlist.tsx, components/JoinList/joinlistelement.tsx, enums/EJoinStatus.ts, package.json, types/Verv.ts
Moved all enums to one designated folder for code improvements. 
Made a new folder called "enums" in the root folder.
=> refactor: move all enums in its own folder

.eslintrc.json, .prettierrc.json, package-lock.json, package.json
New root file `.prettierc.json` that has a set up code-formatting 'rules'.
Added a new config file based on my local options.
=> refacotr: Adds .prettierc config file for default formatting

app/(site)/page.tsx
I sorted the events at the bottom of the main page. 
I saw in the backend that the newer events gets placed behind in an array. Which means that when you fetch the array from sanity you will get the the data in order from oldest to newst. To sort this I simpily revesed the array before storing and rendering it.
=> revesed order of elements in events to sort by newest event

components/events/eventCard.tsx, utils/englishMonth.ts
Some events with a month name different from the English month name (e.g. October) will return "invalid date", due to `new Date()` constructor only accepting English month names. The event's month name (Norwegian) is now converted to English.
Made a new function (and a new file) `getEnglishMonth` that returns the English-equivalent month name.  
Also modified some of the code for the `EventCard` component so that it splits `date` prop into `dayNum` (day number e.g. 26 ) and `monthNorwegian`.
=> fix: event date format

app/(site)/page.tsx, components/events/eventCard.tsx
The section for event cards has been improved: See the differences below:
*Before:*
*After:*
For the event cards-container now uses grid instead of flex. This ensures that every card matches the neighbor's height regardless of the content.  Furthermore, the image for each card has been set to `object-fit` (previously `object-cover`) so that the whole picture is represented (which may contain some important info). Lastly, added smoothing transitions for both the image and the container.  
*Also been tested for mobile-use and seems to be behaving fine.*
=> fix(urgent?): aligns eventcards section properly

app/(site)/page.tsx
Now if the are less than 2 event cards, it's centered, instead of having full width. 
`xl:max-w-${events.length > 1 ? 'full' : 'min'} `
=> fix: event card width

app/globals.css, components/heroSection/hero.tsx, components/navbar/page.tsx, tailwind.config.js
Removed custom screen sizes, and added Tailwind CSS standard sizes. However, made small (sm) size not have a lower boundary so that small phone sizes can view the navbar correctly.
Added animation to item cards on the front page. Just to try it out, and as an example on how we can add small animations to the site, does not need to be added to dev branch. 
Made some small changes to the navigation bar animation. 
Used Framer-motion for animations.
=> Front page animation

next.config.js
The `appDir` configuration has been removed as it's no longer needed 
Removed from `nex.config.js`-file.
=> chore: remove appDir config as it's no longer needed

app/globals.css, components/events/eventCard.tsx
(for instance for-bedrifer page)
*before*
*after*
Removed some css-props. 
```css
@media (prefers-color-scheme: dark) {
:root {
--foreground-rgb: 255, 255, 255;
--background-start-rgb: 0, 0, 0;
--background-end-rgb: 0, 0, 0;
}
}
```
=> fix: dark-mode removed

app/(site)/for-bedrifter/page.tsx, components/Button/button.tsx
I've added a general use button component for the website. It can dynamicly fit to it's parent size or auto size to the text inside. 
Text sizing auto
Text sizing to it's parent
The component needs 2 arguments, which is the text and link. The third which is optional is the sizing. The implmentation of the code is quite straight forward. 
Here is how you can use the component:
```typescript
<Button text='PÅMELDING' link='/' adaptiv={true}/> // adatptiv width is true 
<Button text='PÅMELDING' link='/' adaptiv={false}/> // you could spesify that it's false
<Button text='PÅMELDING' link='/' /> // or not include it 
```
=> Button component

components/header/page.tsx, components/navbar/navbar.tsx
*Before*: 
*After*:
Note: it's no longer sticky (for now). 
Removed pre-existing navbar elements and added these styles the to component:
```css
bg-transparent flex justify-between mx-auto items-center max-w-[877px] min-w-[150px] p-5
```
=> add: new navbar (main)

components/navbar/navbar.tsx
Header now sticks to the hero banner, although it's not perfect. 
`absolute`-positioning, `z-10` etc.
=> fix: header stick to hero banner

app/(site)/for-bedrifter/page.tsx, app/(site)/page.tsx, components/Button/button.tsx, components/frontPage/frontPage.tsx, components/frontPage/frontProp.tsx
* Added frontprop component which takes props which are an image, title and color (optional logo). 
* Fixed text clipping on the front page
* Mobile support
* Just made a generic front component which has the elipse added. 
* If you want to have text over the elipse you should checkout the frontpage component.
=> Front page prop

components/imageTextConatiner.tsx
Fixed a universial size for the images in the imagetextContainer component. Also made the image non clickable when no url is given as argument. 
I used a div for sizing rather then the Image component itself with fill and objectfit to fix size and aspect ratio.
=> Image txt size fix
